-- Baseline: schema pe care clientul o presupune, dar care nu exista nicăieri
-- în repo. Tabelele au fost create manual în Dashboard, iar migrările ulterioare
-- doar le-au făcut `alter table` — deci proiectul nu putea fi reconstruit, iar
-- politicile RLS (singurul lucru care stă între cheia anon publică și datele
-- tuturor) nu erau nicăieri de revizuit.
--
-- Numele fișierului începe cu 00000000_ ca ordinea alfabetică a directorului să
-- fie și ordinea corectă de aplicare. Vezi supabase/README.md.
--
-- Complet idempotent: sigur de rulat pe baza de date existentă. `create table
-- if not exists` sare peste tabelele deja create, iar `add column if not exists`
-- le aduce la zi.

begin;

-- ---------------------------------------------------------------- events -----
create table if not exists public.events (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users (id) on delete cascade,
  user_name       text,
  verse_ref       text not null,
  answer          text,
  chosen          text,
  correct         boolean,
  cycle           integer default 0,
  page_index      integer,
  page_size       smallint,
  chapter_ref     text,
  chapter_size    smallint,
  client_event_id text,
  created_at      timestamptz not null default now(),
  recorded_at     timestamptz not null default now()
);

alter table public.events
  add column if not exists user_id uuid references auth.users (id) on delete cascade,
  add column if not exists user_name text,
  add column if not exists answer text,
  add column if not exists chosen text,
  add column if not exists correct boolean,
  add column if not exists cycle integer default 0,
  add column if not exists page_index integer,
  add column if not exists page_size smallint,
  add column if not exists chapter_ref text,
  add column if not exists chapter_size smallint,
  add column if not exists client_event_id text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists recorded_at timestamptz not null default now();

-- `Prefer: resolution=ignore-duplicates` are nevoie de o constrângere unică pe
-- coloana de conflict, altfel deduplicarea nu se întâmplă niciodată: PostgREST
-- se rezolvă pe cheia primară, iar `id` e generat, deci mereu nou. Rândurile
-- vechi au client_event_id NULL, iar NULL nu intră în conflict cu nimic.
create unique index if not exists events_client_event_id_key
  on public.events (client_event_id);

create index if not exists events_user_id_idx on public.events (user_id);
create index if not exists events_user_cycle_idx on public.events (user_id, cycle);

-- ---------------------------------------------------------------- scores -----
create table if not exists public.scores (
  user_id         uuid primary key references auth.users (id) on delete cascade,
  user_name       text,
  points          integer not null default 0,
  baseline_points integer not null default 0,
  baseline_at     timestamptz,
  current_cycle   integer not null default 0,
  updated_at      timestamptz not null default now()
);

alter table public.scores
  add column if not exists user_name text,
  add column if not exists points integer not null default 0,
  add column if not exists baseline_points integer not null default 0,
  add column if not exists baseline_at timestamptz,
  add column if not exists current_cycle integer not null default 0,
  add column if not exists updated_at timestamptz not null default now();

-- Un singur rând per utilizator. Dacă tabelul existent are duplicate, comanda
-- de mai jos EȘUEAZĂ și întreaga migrare se anulează — intenționat: e o
-- problemă de date care trebuie văzută, nu ocolită în tăcere.
create unique index if not exists scores_user_id_key on public.scores (user_id);

-- ------------------------------------------------------------------- RLS -----
-- Deny-by-default. Clientul citește doar propriile rânduri; clasamentul comun
-- trece exclusiv prin get_public_leaderboard (SECURITY DEFINER), iar scorurile
-- se scriu doar din funcțiile de recalcul, tot SECURITY DEFINER.
--
-- ATENȚIE la aplicarea pe baza de date existentă: aceste comenzi ADAUGĂ
-- politicile corecte, dar nu pot șterge politicile permisive create manual,
-- ale căror nume nu le cunosc. Listează-le întâi și șterge ce nu apare aici:
--   select schemaname, tablename, policyname, cmd, qual, with_check
--   from pg_policies where schemaname = 'public';

alter table public.events enable row level security;

drop policy if exists events_insert_own on public.events;
create policy events_insert_own on public.events
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists events_select_own on public.events;
create policy events_select_own on public.events
  for select to authenticated
  using (user_id = auth.uid());

-- Fără politici de UPDATE/DELETE: istoricul de răspunsuri e append-only.

alter table public.scores enable row level security;

drop policy if exists scores_select_own on public.scores;
create policy scores_select_own on public.scores
  for select to authenticated
  using (user_id = auth.uid());

-- Fără politici de scriere: doar funcțiile SECURITY DEFINER modifică scorurile.

-- ---------------------------------------------------------- get_own_score ----
-- Clientul apela deja acest RPC (js/tracker.js), dar nu era definit în repo.
-- Clasamentul public e plafonat; asta întoarce scorul propriu chiar și pentru
-- cine e în afara clasamentului afișat.
create or replace function public.get_own_score()
returns integer
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (select s.points from public.scores s where s.user_id = auth.uid()),
    0
  )::integer;
$$;

revoke all on function public.get_own_score() from public;
grant execute on function public.get_own_score() to authenticated;

commit;
